apiVersion: v1
kind: Service
metadata:
  name: mount-hostpath-svc
  labels:
    app: webhook-mount-hostpath
  #namespace: ${namespace}
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: webhook-mount-hostpath
