apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mount-hostpath
  labels:
    app: mount-hostpath
webhooks:
  - name: mount-hostpath.99bill.com
    clientConfig:
      service:
        name: mount-hostpath-svc
        namespace: ${namespace}
        path: "/mutate"
      caBundle: ${CA_BUNDLE}
    rules:
    - apiGroups:
      - extensions
      apiVersions:
      - v1beta1
      operations:
      - CREATE
      - UPDATE
      resources:
      - deployments
    - apiGroups:
      - apps
      apiVersions:
      - 'v1'
      operations:
      - CREATE
      - UPDATE
      resources:
      - deployments
    namespaceSelector:
      matchLabels:
        99bill-webhook/validate: "true"

