apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mount-hostpath-cr
  labels:
    app: mount-hostpath
rules:
- apiGroups:
  - banzaicloud.com
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - events
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - autoscaling
  resources:
  - '*'
  verbs:
  - '*'