kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mount-hostpath-deployment-crb 
  labels:
    app: mount-hostpath
subjects:
- kind: ServiceAccount
  name: mount-hostpath-deployment-sa
  namespace: pipeline-infra
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mount-hostpath-deployment-cr